# Generated by Django 4.2.26 on 2025-11-21 18:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "proforma",
                    models.FileField(blank=True, null=True, upload_to="proformas/"),
                ),
                (
                    "proforma_metadata",
                    models.JSONField(
                        blank=True, help_text="Extracted proforma data", null=True
                    ),
                ),
                (
                    "purchase_order",
                    models.FileField(
                        blank=True, null=True, upload_to="purchase_orders/"
                    ),
                ),
                (
                    "purchase_order_metadata",
                    models.JSONField(
                        blank=True, help_text="Generated PO data", null=True
                    ),
                ),
                (
                    "receipt",
                    models.FileField(blank=True, null=True, upload_to="receipts/"),
                ),
                (
                    "receipt_metadata",
                    models.JSONField(
                        blank=True, help_text="Extracted receipt data", null=True
                    ),
                ),
                (
                    "receipt_validation",
                    models.JSONField(
                        blank=True, help_text="Receipt validation results", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "purchase_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("staff", "Staff"),
                            ("approver_level_1", "Approver Level 1"),
                            ("approver_level_2", "Approver Level 2"),
                            ("finance", "Finance"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase_requests.purchaserequest",
                    ),
                ),
            ],
            options={
                "db_table": "request_items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "approver_level",
                    models.IntegerField(
                        choices=[(1, "Level 1"), (2, "Level 2")],
                        help_text="1 for Level 1 approver, 2 for Level 2 approver",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        blank=True,
                        help_text="True=Approved, False=Rejected, None=Pending",
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="purchase_requests.purchaserequest",
                    ),
                ),
            ],
            options={
                "db_table": "approvals",
                "ordering": ["approver_level", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="purchaserequest",
            index=models.Index(
                fields=["status", "-created_at"], name="purchase_re_status_f43ba2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequest",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="purchase_re_created_2b6b2b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["purchase_request", "approver_level"],
                name="approvals_purchas_24b1ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="approval",
            index=models.Index(
                fields=["approver", "-created_at"], name="approvals_approve_1f594d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="approval",
            unique_together={("purchase_request", "approver_level")},
        ),
    ]
